---
version: "3.5"

x-taiga-environment: &taiga-environment
  TAIGA_SITES_SCHEME: "${TAIGA_SCHEME:-http}"
  TAIGA_SITES_DOMAIN: "${TAIGA_DOMAIN:-localhost:9000}"
  TAIGA_SUBPATH: "${TAIGA_SUBPATH}"
  PUBLIC_REGISTER_ENABLED: "${PUBLIC_REGISTER_ENABLED:-False}"
  ENABLE_SLACK: "${ENABLE_SLACK:-False}"
  ENABLE_JIRA_IMPORTER: "${ENABLE_JIRA_IMPORTER:-False}"

x-db-environment: &db-environment # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: "${TAIGA_DB_PASSWORD}"

x-rabbitmq-back-environment:
  &rabbitmq-back-environment # For rabbitMQ "consumers"
  RABBITMQ_USER: "${RABBITMQ_USER:-taiga}"
  RABBITMQ_PASS: "${RABBITMQ_PASS:-taiga}"

x-rabbitmq-server-environment:
  &rabbitmq-server-environment # For rabbitMQ "server"
  RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
  RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-taiga}"
  RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-taiga}"
  RABBITMQ_DEFAULT_VHOST: "taiga"

x-openid-environment-front: &openid-environment-front
  ENABLE_OPENID: "${ENABLE_OPENID:-False}"
  OPENID_NAME: "${OPENID_NAME}"
  OPENID_CLIENT_ID: "${OPENID_CLIENT_ID}"
  OPENID_URL: "https://${OPENID_KEYCLOAK_HOSTNAME}/auth/realms/${OPENID_KEYCLOAK_REALM}/protocol/openid-connect/auth"
  OPENID_SCOPE: "${OPENID_SCOPE:-openid email}"
  OPENID_FILTER_FIELD: "${OPENID_FILTER_FIELD}"
  OPENID_FILTER: "${OPENID_FILTER}"
  OPENID_ID_FIELD: "${OPENID_ID_FIELD:-sub}"
  OPENID_USERNAME_FIELD: "${OPENID_USERNAME_FIELD:-preferred_username}"
  OPENID_FULLNAME_FIELD: "${OPENID_FULLNAME_FIELD:-name}"
  OPENID_EMAIL_FIELD: "${OPENID_EMAIL_FIELD:-email}"

x-openid-environment-back: &openid-environment-back
  <<: *openid-environment-front
  OPENID_USER_URL: "https://${OPENID_KEYCLOAK_HOSTNAME}/auth/realms/${OPENID_KEYCLOAK_REALM}/protocol/openid-connect/userinfo"
  OPENID_TOKEN_URL: "https://${OPENID_KEYCLOAK_HOSTNAME}/auth/realms/${OPENID_KEYCLOAK_REALM}/protocol/openid-connect/token"
  OPENID_CLIENT_SECRET: "${OPENID_CLIENT_SECRET}"

x-back-environment: &back-environment
  <<: *db-environment
  <<: *rabbitmq-back-environment
  <<: *taiga-environment
  <<: *openid-environment-back
  # Check https://github.com/taigaio/taiga-back/blob/master/docker/config.py
  POSTGRES_HOST: taiga-db
  TAIGA_SECRET_KEY: "${TAIGA_SECRET_KEY}"
  ENABLE_TELEMETRY: "${TAIGA_ENABLE_TELEMETRY:-True}"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL:-no-reply@example.com}"
  EMAIL_USE_TLS: "${EMAIL_USE_TLS:-False}"
  EMAIL_USE_SSL: "${EMAIL_USE_SSL:-False}"
  EMAIL_HOST: "${EMAIL_HOST:-smtp.host.example.com}"
  EMAIL_PORT: ${EMAIL_PORT:-587}
  EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
  # Plugins
  JIRA_IMPORTER_CONSUMER_KEY: "${JIRA_IMPORTER_CONSUMER_KEY}"
  JIRA_IMPORTER_CERT: "${JIRA_IMPORTER_CERT}"
  JIRA_IMPORTER_PUB_CERT: "${JIRA_IMPORTER_PUB_CERT}"

x-front-environment: &front-environment
  <<: *taiga-environment
  <<: *openid-environment-front

x-protected-environment: &protected-environment
  <<: *taiga-environment # for TAIGA_SUBPATH
  SECRET_KEY: "${TAIGA_SECRET_KEY}"

x-volumes: &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  - ./taiga-back/env-setting-entrypoint.sh:/usr/local/bin/env-setting-entrypoint.sh
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-db:
    image: postgres:12.3
    environment:
      <<: *db-environment
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: ${TAIGA_IMAGE_BACK:-taigaio/taiga-back:latest}
    environment:
      <<: *back-environment
    volumes: *default-back-volumes
    entrypoint: "/usr/local/bin/env-setting-entrypoint.sh"
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: ${TAIGA_IMAGE_BACK:-taigaio/taiga-back:latest}
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment:
      <<: *back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      <<: *rabbitmq-server-environment
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: ${TAIGA_IMAGE_FRONT:-taigaio/taiga-front:latest}
    environment:
      <<: *front-environment
    networks:
      - taiga
    volumes:
      - ./taiga-front/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./taiga-front/docker-entrypoint.d/00-set-taiga-env.envsh:/docker-entrypoint.d/00-set-taiga-env.envsh
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      <<: *back-environment
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      <<: *rabbitmq-server-environment
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      <<: *protected-environment
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "${TAIGA_GATEWAY_PORT:-9000}:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
